config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :cities do
    resources :posts
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.order(created_at: :desc).all
  end

  def show
    @city = City.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @cities = City.order(created_at: :desc).all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def create
    @city = City.find(params[:city_id])
    @city.posts.create(post_params)
    redirect_to city_path(@city)
  end

  def show
    city = City.find(params[:city_id])
    @post = city.posts.find(params[:id])
  end

  def new
    @city = City.find params[:city_id]
  end

  def edit
    @city = City.find params[:city_id]
    @post = Post.find(params[:id])
  end

  def update
    @city = City.find params[:city_id]
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to @city
  end

  def destroy
      @city = City.find params[:city_id]
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to city_path(@city)
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/cities/_carousel.html.erb
<!-- Carousel partial -->
<div class="carousel-div">
  <div class="slider">

    <ul class="slides">
      <%= @cities.each do |city| %>

         <li>
           <%= link_to (image_tag(city.photoURL)), city_path(city) %>
         </li>
      <% end %>
    </ul>

  </div>
</div>

app/views/cities/index.html.erb
<!-- renders carousel partial -->
<div>
  <%= render 'cities/carousel' %>
</div>


<!-- Displays each city on index page in a card that is a clickable link -->
<div class="row">
    <% @cities.each do |city| %>
    <div class="col s12 m4 center">
        <div class="card">
            <div class="card-image">
                <%= link_to image_tag(city.photoURL), city %>
                <span class="card-title city-title name-tag"><%= link_to city.name, city %></span>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/cities/show.html.erb
<h1><%= @city.name %></h1>

<%= image_tag(@city.photoURL) %>

<div class="new-post-button">
    <%= link_to "New Post", new_city_post_path(@city), class: "waves-effect waves-light btn-large right" %>
</div>

<!-- loops through and displays info for each city post -->
<div class="row">
<% @city.posts.order(created_at: :desc).each do |post| %>
        <div class="col s12 m4w city-card">
            <div class="card blue-grey lighten-1">
                <div class="card-content white-text">
                    <!-- <span class="card-title"><%= post.title %></span> -->
                    <span class="card-title">
                        <%= link_to post.title, city_post_path(@city.id, post.id) %>
                    </span>
                    <p><%= time_ago_in_words post.created_at.to_datetime %>
                        ago</p>
                    <p><%= post.body %></p>
                </div>
                <div class="card-action">
                    <%= link_to 'Edit', edit_city_post_path(@city.id, post.id) %>
                    <%= link_to 'Delete', city_post_path(@city.id, post.id),
                          method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/home/_footer.html.erb
<footer class="page-footer deep-orange darken-4">
  <div class="container">
    <div class="row">
      <div class="footer">
        <div class="container center">
          <h6>explore your world</h6>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container center">
      © 2017 WDI Group 2
    </div>
  </div>
</footer>

app/views/home/_navbar.html.erb
<nav>
  <div class="nav-wrapper deep-orange darken-4">

    <a href="<%= cities_path %>" class="brand-logo center">tourvia</a>

  </div>
</nav>

app/views/home/_new_post_form.html.erb
<!-- Modal Structure -->
<div id="new-post-modal" class="modal">
  <div class="modal-content">
    <h4>Modal Header</h4>

    <%= form_for :post, url: new_city_post_path(:post), html: { class: 'form-horizontal'} do %>

        <div class="row">
          <form class="col s12">
            <div class="row">
              <div class="input-field col s12">
                <input placeholder="Title" id="post_title" type="text" name="post[title]">
                <label for="post_title">Title</label>
              </div>

            </div>

            <div class="input-field col s12">
              <textarea id="post_body" class="materialize-textarea" data-length="120" name="post[body]"></textarea>
              <label for="post_body">Comment</label>
            </div>

          </form>
        </div>

        <button class="btn waves-effect waves-light" type="submit" name="POST">Submit
          <i class="material-icons right">send</i>
        </button>
    <% end %>

  </div>
</div>

app/views/home/index.html.erb
<div class="banner">
    <h1>Explore your world.</h1>
    <div>
        <%= link_to "Enter", cities_path, class: "waves-effect waves-light btn-large" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>tourvia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link href="https://fonts.googleapis.com/css?family=Lobster|Oswald" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <%= yield %>
    <%= render 'home/footer' %>
  </body>
</html>

app/views/posts/_new_post_form.html.erb
<%= form_for ([@city, @city.posts.build]) do |f| %>

    <div class="row">

      <div class="row">
        <div class="input-field col s12">
          <%= f.label :title %>
          <%= f.text_field :title %>
        </div>

      </div>

      <div class="input-field col s12">
        <%= f.label :body %>
        <%= f.text_area :body %>
      </div>

    </div>


    <%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<%= form_for ([@city, @post]) do |f| %>

<div class="row">

    <div class="row">
        <%= f.label :title %>
        <div class="input-field col s12">
            <%= f.text_field :title %>
        </div>

    </div>

    <%= f.label :body %>
    <div class="input-field col s12">
        <%= f.text_area :body %>
    </div>

</div>

<%= f.submit class: "waves-effect waves-light btn" %>

<% end %>

app/views/posts/new.html.erb
<%= form_for ([@city, @city.posts.build]) do |f| %>

<div class="row">

    <div class="row">
        <%= f.label :title %>
        <div class="input-field col s12">
            <%= f.text_field :title %>
        </div>

    </div>

    <%= f.label :body %>
    <div class="input-field col s12">
        <%= f.text_area :body %>
    </div>

</div>

<%= f.submit class: "waves-effect waves-light btn" %>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h3><%= @post.city.name %></h3>
<p><%= @post.body %></p>